#!/usr/bin/env python

from velocity_publisher import computation

import rospy
from geometry_msgs.msg import Twist

# Build and publish messages to the cmd_vel topic
def move_robot():

    rospy.init_node("cmd_vel_publisher", anonymous=True)

    # Create a publisher
    pub = rospy.Publisher("cmd_vel", Twist, queue_size=10)
    # Create a message of type Twist
    message = Twist()
    # Build message for linear and angular velocity
    message.linear.x = 2   
    message.angular.z = 1  
    # Publish rate
    rate = rospy.Rate(1)

    # Publish messages until node is shutdown
    while not rospy.is_shutdown():
        pub.publish(message)
        rate.sleep()


if __name__ == "__main__":
    move_robot()
